import matplotlib.pyplot as plt
import json
import numpy as np

# File generated by this data structure
# out['{nvis}_{nhid}'.format(nvis=nvis, nhid=nhid)] = t1-t0
timings = json.load(open('timings.json'))

nvis = []
nhid = []
time = []
for k, v in timings.items():
	nv, nh = k.split('_')
	nvis.append(int(nv))
	nhid.append(int(nh))
	time.append(v)
nvis = np.array(nvis)
nhid = np.array(nhid)
time = np.array(time)

markers = ['o', 'v', 'x']
nhids = sorted(list(set(nhid)))

fig = plt.figure(figsize=(4, 2.5))
ax = fig.add_subplot(111)
for nh, m in zip(nhids, markers):
	idx = nhid == nh
	ax.plot(nvis[idx], time[idx], m, c='black', label=r'CPU, $N_{h}$='f'{nh}')
ax.axhline(5., c='k', ls='--', label='BSS-2')

ax.legend()
ax.set_xlabel('system size $N$')
ax.set_yticks([0., 5., 10., 15.])
ax.set_ylabel(r'time per $10^6$ samples [sec]')
plt.tight_layout()
plt.savefig('figure6.pdf')